language: go

go:
 - 1.8.1

before_install:
  # Coverage tools
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge

install:
- go get -t ./...

# Unconditionally place the repo at GOPATH/src/${go_import_path} to support
# forks.
go_import_path: github.com/m-lab/alertmanager-github-receiver

script:
# Run unit tests.
- go test -covermode=count -coverprofile=alerts.cov -v github.com/m-lab/alertmanager-github-receiver/alerts
- go test -covermode=count -coverprofile=issues.cov -v github.com/m-lab/alertmanager-github-receiver/issues

# Coveralls
- $HOME/gopath/bin/gocovmerge alerts.cov issues.cov > merge.cov
- $HOME/gopath/bin/goveralls -coverprofile=merge.cov -service=travis-ci
